name: UAT to Production EC2 Deploy

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Git Tag (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  build-deploy-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_tag }}

      - name: Prepare Files for UAT
        run: |
          mkdir -p deploy_output
          sed "s/REPLACE_ENV/UAT/g; s/REPLACE_TAG/${{ github.event.inputs.release_tag }}/g" index.html > deploy_output/index.html
          cp test.txt deploy_output/

      - name: Deploy to UAT EC2
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.UAT_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy_output/*"
          target: "/var/www/my-app/"

      - name: Restart Nginx on UAT EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.UAT_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx

  deploy-to-prod:
    needs: build-deploy-uat
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: http://${{ secrets.PROD_EC2_HOST }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_tag }}

      - name: Prepare Files for Production
        run: |
          mkdir -p deploy_output
          sed "s/REPLACE_ENV/Production/g; s/REPLACE_TAG/${{ github.event.inputs.release_tag }}/g" index.html > deploy_output/index.html
          cp test.txt deploy_output/

      - name: Deploy to Production EC2
        uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy_output/*"
          target: "/var/www/my-app/"

      - name: Restart Nginx on Production EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart nginx

