name: SSH-Controlled EC2 Deploy (User A/B)

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Git Tag (e.g., v1.0.0)'
        required: true
        type: string
      target_user: 
        description: 'Target User (A or B)'
        required: true
        type: choice
        options:
          - A
          - B

jobs:
  build-deploy-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_tag }}

      - name: Prepare Files for UAT
        run: |
          echo "Preparing files for UAT environment..."
          mkdir -p deploy_output
          sed "s/REPLACE_ENV/UAT/g; s/REPLACE_TAG/${{ github.event.inputs.release_tag }}/g" index.html > deploy_output/index.html
          cp test.txt deploy_output/
          ls -l deploy_output/

      - name: Securely Copy UAT Files to Server
        env:
          SSH_KEY: ${{ github.event.inputs.target_user == 'A' && secrets.A_SSH_PRIVATE_KEY || secrets.B_SSH_PRIVATE_KEY }}
          UAT_HOST: ${{ github.event.inputs.target_user == 'A' && secrets.A_UAT_EC2_HOST || secrets.B_UAT_EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          tar -czf app_deploy.tar.gz -C deploy_output .
          scp -o StrictHostKeyChecking=no -i deploy_key.pem app_deploy.tar.gz ${USER_NAME}@${UAT_HOST}:/tmp/

      - name: Deploy and Restart Nginx on UAT-Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ github.event.inputs.target_user == 'A' && secrets.A_UAT_EC2_HOST || secrets.B_UAT_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ github.event.inputs.target_user == 'A' && secrets.A_SSH_PRIVATE_KEY || secrets.B_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop nginx
            sudo rm -rf /var/www/html/*
            sudo tar -xzf /tmp/app_deploy.tar.gz -C /var/www/html/
            sudo rm /tmp/app_deploy.tar.gz
            sudo chmod -R 755 /var/www/html
            sudo systemctl start nginx
            ls -l /var/www/html/
            echo "UAT Deployment Complete!"

  deploy-to-prod:
    needs: build-deploy-uat
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.release_tag }}

      - name: Prepare Files for Production
        run: |
          echo "Preparing files for Production environment..."
          mkdir -p deploy_output
          sed "s/REPLACE_ENV/Production/g; s/REPLACE_TAG/${{ github.event.inputs.release_tag }}/g" index.html > deploy_output/index.html
          cp test.txt deploy_output/
          echo "Source files prepared for Production deployment:"
          ls -l deploy_output/

      - name: Securely Copy Production Files to Server
        env:
          SSH_KEY: ${{ github.event.inputs.target_user == 'A' && secrets.A_SSH_PRIVATE_KEY || secrets.B_SSH_PRIVATE_KEY }}
          PROD_HOST: ${{ github.event.inputs.target_user == 'A' && secrets.A_PROD_EC2_HOST || secrets.B_PROD_EC2_HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
        run: |
          echo "$SSH_KEY" > deploy_key.pem
          chmod 600 deploy_key.pem
          tar -czf app_deploy.tar.gz -C deploy_output .
          scp -o StrictHostKeyChecking=no -i deploy_key.pem app_deploy.tar.gz ${USER_NAME}@${PROD_HOST}:/tmp/

      - name: Deploy and Restart Nginx on Production-Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ github.event.inputs.target_user == 'A' && secrets.A_PROD_EC2_HOST || secrets.B_PROD_EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ github.event.inputs.target_user == 'A' && secrets.A_SSH_PRIVATE_KEY || secrets.B_SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop nginx
            sudo rm -rf /var/www/html/*
            sudo tar -xzf /tmp/app_deploy.tar.gz -C /var/www/html/
            sudo rm /tmp/app_deploy.tar.gz
            sudo chmod -R 755 /var/www/html
            sudo systemctl start nginx
            ls -l /var/www/html/
            echo "Production Deployment Complete!"
